mozaggregator/aggregator.py, mozaggregator/db.py, setup.py
I have limited the number of partitions and got rid of the groupBy operation to reduce the memory pressure. See [Bug 1229738](https://bugzilla.mozilla.org/show_bug.cgi?id=1229738).
=> Reduce memory pressure

mozaggregator/aggregator.py, setup.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1271961.
=> Handle invalid data.

mozaggregator/aggregator.py, setup.py
The get_pings API has been deprecated.
Our tests don't test this, but this works manually. @vitillo, r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozaggregator/20)
=> Bug 1316721 - Use Dataset API

mozaggregator/aggregator.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozaggregator/23)
=> Deal with unexpected types when checking if telemetry is enabled.

mozaggregator/service.py, setup.py
@vitillo r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozaggregator/26)
=> Bug 1299840 - Log requests against aggregator service

mozaggregator/aggregator.py, mozaggregator/db.py, mozaggregator/scalar.py, mozaggregator/service.py, setup.py, tests/dataset.py, tests/test_aggregator.py, tests/test_db.py, tests/test_scalar.py
This does not include numeric scalars in child payloads.
@vitillo r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozaggregator/22)
=> Bug 1281208 - Aggregate numeric scalars

mozaggregator/aggregator.py, mozaggregator/db.py, mozaggregator/service.py, tests/dataset.py, tests/test_aggregator.py, tests/test_db.py
This is surprisingly less-complicated than I feared.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozaggregator/29)
=> Bug 1314227 - GPU process telemetry support for aggregator

mozaggregator/aggregator.py, tests/dataset.py, tests/test_aggregator.py, tests/test_db.py
=> Bug 1319610 - Aggregate process and gpu scalars

ansible/dev.yml, ansible/roles/spark/tasks/main.yml
See https://bugzilla.mozilla.org/show_bug.cgi?id=1344020.
=> Run tests against Spark 2.0.2

mozaggregator/config.py, mozaggregator/db.py, mozaggregator/service.py, setup.py
Tested this locally. Service starts and reads from the correct DB. Aggregates writes to the correct DB.
@vitillo r?
=> Bug 1340185 - Add read replica for service

mozaggregator/service.py, setup.py
Also dropped retries a few notches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozaggregator/48)
=> Ignore stream describe throttling

mozaggregator/service.py, setup.py, tests/test_db.py
=> Make missing scalars 404

README.md
Fixing readme badge and bash commands
=> Fixing readme badge and bash commands

Dockerfile, Dockerfile.dev, README.md, mozaggregator/db.py, setup.py, tests/test_db.py
This extends the "ignore null labels"
to any dimensions with null values.
=> Bug 1467860 - Ignore aggregates with null chars

.circleci/config.yml
[Bug 1473094] Migrating to circleci 2.0 - fixing deployment to not use image cache
=> [Bug 1473094] Migrating to circleci 2.0 - fixing deployment to not use image cache

.circleci/config.yml, Dockerfile, Dockerfile.dev
This updates the container to use spark installed by pip.
=> Use pyspark installed from pip

Dockerfile, Dockerfile.dev, docker-compose.yml, requirements/build.txt, requirements/tests.txt, tests/conftest.py, tests/test_fixtures.py, tests/utils.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1594448)
This adds test fixtures for accessing all the necessary test fixtures from gcs.
=> Bug 1594448 - Add test fixtures for reading from avro data

mozaggregator/cli.py, tests/test_db.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1596917)
=> Bug 1596917 - Skip reading credentials file if not exists

mozaggregator/mobile.py
Each submission of data is < 50mb, so this should be a single file per submission date to avoid creating extra files.
=> Change num_partitions for mobile_aggregates

.circleci/config.yml, bin/README.md, mozaggregator/aggregator.py, mozaggregator/parquet.py, requirements/build.txt, tests/conftest.py, tests/test_parquet.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1656910
=> [Bug 1656910] Remove saved-session ping processing

requirements/build.txt, setup.py
Python moztelemetry url http to https
=> Python moztelemetry url http to https
