ansible/deploy.yml
`App` and `Type` are the tags we use for accounting. We're going to use `pipeline` as the `App` for anything related to the data pipeline, and use `Type` to further match specific applications such as telemetry.
=> Standardize tags for accounting purposes

README.md, mozaggregator/service.py
As reported by :canuckistani, the MIME type in the API responses are text/html, when they should actually be application/json.
=> Fix MIME types in API response

mozaggregator/aggregator.py, tests/dataset.py, tests/test_aggregator.py
See [Bug 1275010](https://bugzilla.mozilla.org/show_bug.cgi?id=1275010) and [Bug 1275019](https://bugzilla.mozilla.org/show_bug.cgi?id=1275019).
=> Ignore keyed histograms with an excessive number of labels.

mozaggregator/aggregator.py, setup.py, tests/dataset.py, tests/test_aggregator.py, tests/test_db.py
When bug 1218576 lands, Firefox will start sending child histograms in
.processes.child.{keyedH|h}istograms
instead of
.childPayloads[i].{keyedH|h}istograms
Handle pings that have child histograms in either (or a mix of both) config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozaggregator/17)
=> Bug 1286951 - Update mozaggregator to account for change in childPayloads

setup.py, tests/dataset.py, tests/test_db.py
Luckily, this was basically already supported. These tests show how to take the result and use it to recreate the categorical histogram with correct labels.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozaggregator/19)
=> Bug 	1297060 - Add support for categorical histograms

mozaggregator/aggregator.py, setup.py
Saved_session pings are being deprecated.
However, main pings are both opt-in and opt-out, while saved_session
were just opt-in. For this reason we are filtering to include only
opt-in users, so the results should be similar.
Note that results will not be identical, since saved_session pings
often lag main pings, due to the main ping submission on date split.
For information about how this was tested and how long it took, see the associated bug.
@vitillo r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozaggregator/21)
=> Bug 1286868 - Use main pings instead of saved_session

mozaggregator/db.py, setup.py, tests/test_db.py
Postgres doesn't handle char \u0000, so we'll have to ignore it.
We can't just use printable chars, since there aren't any requirements
for keyed histograms labels to be limited to those.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozaggregator/24)
=> Handle null unicode char in labels

mozaggregator/aggregator.py, setup.py
I tested this on data from `20170130`. I used the `telemetry_aggregator.py` we use for airflow. I ran it on 100% of the data and saw no errors.
@vitillo r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozaggregator/31)
=> Bug 1336119 - Aggregate Fennec saved-session pings

mozaggregator/service.py, mozaggregator/sql.py, tests/dataset.py, tests/test_db.py
With the change to add gpu histograms, the values for "child"
went from true/false to "true"/"false"/"gpu". This means that
querying for {"child": True} only returns data from before
we made that change [0].
With this change, we now query for both {"child": True}
and for {"child": "true"}. The database function is
also backwards compatible, just in case anyone is running
an older version of the service.
[0] https://github.com/mozilla/python_mozaggregator/pull/29
=> Bug 1339139 - Fix retrieval of child/parent histograms

mozaggregator/service.py
Previously, logging was done for referer URL and referer.
Unfortunately, the data was not properly accessed, so the fields
were never present. This change fixes that by properly retrieving
HTTP Referer, and also using HTTP Origin.
@vitillo r? I tested this with cURL.
=> Bug 1299840 - Change logging to include Origin

mozaggregator/service.py, tests/test_db.py
In https://github.com/mozilla/python_mozaggregator/pull/29, we
added the new processes to the get_filter_options, but not to
get_metrics (so they weren't correctly transformed for querying
the database). This change transforms content => true and
parent => false for child GET params.
@chutten r?
=> Bug 1339139 - Enable content/parent process types

mozaggregator/service.py, setup.py, tests/test_db.py
This change implements both cache control and ETag headers.
For Cache-Control:
For all requests but submission-date aggregates, the max-age
is set until the start of the next load of the database
(we know the data won't change until then).
If the request is during a load, max-age is set to 0.
For submission-date aggregates, max-age is always set to 24h.
ETags:
Etags are not set on any requests but submission-date aggregates.
The ETags are the same for all values, since submission-date
aggregates will never change, unless we do a backfill.
Thus, the single ETag value can be updated, invalidating all
previous ETags. This should only be done after a backfill.
@vitillo r?
=> Bug 1336000 - Add Cache Control and ETag headers

mozaggregator/service.py
Thoughts on ignoring failures? Should only happen briefly on high usage. We can also request to increase our limits which should fix this problem in the future.
Also fixes a bug where the response from cloudwatch logs is
never set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozaggregator/46)
=> Ignore cloudwatch log upload failures

mozaggregator/sql.py, setup.py, tests/test_db.py
This separates aggregating the histogram buckets (keys 0:n-2)
from the sum and ping counts (keys n-1 and n). This way we can
add new buckets without the new values polluting those last
two buckets.
Testing: I don't really have a way to add a direct test of this situation, which is a change in the histogram definition. As such I've tested that this aggregate function works as expected, and when used on the histograms of different lengths should aggregate them correctly as well.
=> Bug 1403994 - Aggregate histograms of different lengths correctly

mozaggregator/sql.py, setup.py
Bug 1403994
Previously, old build_id histograms would merge with new ones
by just adding; but instead we want to first add the histograms,
then the sums and counts separately.
Unfortunately this means that [0] did not fix historical build_id
aggregates. Those are broken in the db for good.
[0] https://github.com/mozilla/python_mozaggregator/pull/57
=> Make build_id insertions add histograms correctly

mozaggregator/aggregator.py, mozaggregator/service.py, mozaggregator/sql.py, tests/test_aggregator.py, tests/test_db.py
[bug 1412382](https://bugzilla.mozilla.org/show_bug.cgi?id=1412382)
Use counters in the database are wrong, and have been since [bug 1204994](https://bugzilla.mozilla.org/show_bug.cgi?id=1204994) changed
_extract_main_histograms. It only counted "False" values in pings that had at
least one "True" value (because if there were only "False" values, we didn't
send a use counter in that ping).
This fixes this by subbing in the False value from
(TOP_LEVEL_)CONTENT_DOCUMENTS_DESTROYED, which has the correct number.
This results in an interesting side-effect that use counters that don't exist
will get valid responses from the service. This is because the service can't
tell the difference between a use counter that doesn't exist and one that just
didn't happen to have a single 'True' value in …
=> Fix Use Counters at the Service Level

setup.py
The recent change of use counters necessitates a minor version
bump, since the API remains the same but the data returned
is different.
=> Increase version to 0.3

mozaggregator/sql.py, tests/test_db.py
This logs warnings in PostgreSQL whenever we truncate, including the pre-truncation value so we have evidence of how severe the truncation is.
=> Bug 1472621 Truncate aggregates on bigint overflow

mozaggregator/db.py, requirements/tests.txt, tests/test_db.py
Note that this continues to log messages on the DB side, so does not address concern (2) in https://github.com/mozilla/python_mozaggregator/pull/99#pullrequestreview-135824877 but I think the simplicity of this approach vs. a purely client-side approach makes it a better option.
=> Bug 1474590 Client-side logging for database warnings

queries/drop_non_quantum.sql
Before we migrate to GCP, we'd like to trim the database a bit. This query should remove all data from before `20180101`.
We will keep backups of data before then. If a use-case comes up for that data, we can spin up a database and query it there.
I've tested this query by running the following, which is almost a replica of what the drop_tables is doing. It correctly returned the `max_date` as `20150331`. Running with `20180101` correctly gives `20180101`.
There is a nice side benefit of this query, which is it drops all those "weird" builds that we never use anyways - they're not queryable from the service.
```
CREATE OR REPLACE FUNCTION try_cast_int(p_in TEXT, p_default INT default null)
RETURNS INT
LANGUAGE plpgsql
AS $$
BEGIN
BEGIN
RETURN $1::INT;
EXCEPTION 
WHEN others THEN
RETURN …
```
=> Add drop tables query

Dockerfile, Dockerfile.dev, bin/dataproc.sh, docker-compose.yml, mozaggregator/aggregator.py, mozaggregator/bigquery.py, mozaggregator/cli.py, mozaggregator/mobile.py, mozaggregator/parquet.py, requirements/build.txt, requirements/tests.txt, tests/conftest.py, tests/decoded.1.bq, tests/test_db.py, tests/test_mobile.py, tests/test_parquet.py, tests/utils.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1572112)
I've generated two datasets that complete successfully for `mobile_metrics_aggregates` and `aggregates_poc`.
```bash
bin/dataproc.sh \
mobile \
--output gs://amiyaguchi-dev/mozaggregator/mobile_test/v1/ \
--num-partitions 200 \
--date 20191019 \
--source bigquery \
--project-id moz-fx-data-shar-nonprod-efed
bin/dataproc.sh \
parquet \
--output gs://amiyaguchi-dev/mozaggregator/parquet_test/v1/ \
--num-partitions 200 \
--date 20191020 \
--channels nightly,beta \
--source bigquery \
--project-id moz-fx-data-shar-nonprod-efed
```
I've done some very minor testing, but I still need to verify that the resulting aggregates are matching. From a cursory glance, it looks like the `mobile_metrics_aggregates` table hasn't been updated …
=>  Bug 1572112 - Add support for GCP payload_bytes_decoded to python_mozaggregator

bin/dataproc.sh, mozaggregator/aggregator.py, mozaggregator/bigquery.py, mozaggregator/cli.py, tests/conftest.py, tests/test_db.py, tests/test_fixtures.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1594448)
```bash
bq extract \
--destination_format=AVRO \
'moz-fx-data-shar-nonprod-efed:payload_bytes_decoded.telemetry_telemetry__main_v4$20191101' \
'gs://amiyaguchi-dev/avro-dump-test/20191101/main_v4/*.avro'
bq extract \
--destination_format=AVRO \
'moz-fx-data-shar-nonprod-efed:payload_bytes_decoded.telemetry_telemetry__saved_session_v4$20191101' \
'gs://amiyaguchi-dev/avro-dump-test/20191101/saved_session_v4/*.avro'
NUM_WORKERS=5 bin/dataproc.sh \
aggregator \
--credentials-protocol s3 \
--credentials-bucket telemetry-spark-emr-2 \
--credentials-prefix aggregator_dev_database_envvars.json \
--num-partitions 200 \
--date 20191101 \
--source avro \
--avro-prefix gs://amiyaguchi-dev/avro-dump-test
```
=>  Bug 1594448 - Add option to aggregator to read from avro

bin/dataproc.sh, bin/export-avro.sh, mozaggregator/bigquery.py, mozaggregator/cli.py, mozaggregator/mobile.py, mozaggregator/parquet.py, requirements/tests.txt, tests/conftest.py, tests/test_fixtures.py, tests/test_mobile.py, tests/test_parquet.py, tests/utils.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1594448)
This follows up with #198 to add avro support to mobile aggregates and parquet. It's much easier to verify the outputs of the parquet datasets over the aggregates postgres database. 
```
bin/export-avro.sh moz-fx-data-shar-nonprod-efed gs://amiyaguchi-dev/avro-mozaggregator 20191101
bin/export-avro.sh moz-fx-data-shar-nonprod-efed gs://amiyaguchi-dev/avro-mozaggregator 20191101
NUM_WORKERS=5 bin/dataproc.sh \
mobile \
--output gs://amiyaguchi-dev/mozaggregator/mobile_test/nonprod/20191101/ \
--num-partitions 200 \
--date 20191101 \
--source avro \
--avro-prefix gs://amiyaguchi-dev/avro-mozaggregator/moz-fx-data-shar-nonprod-efed
NUM_WORKERS=5 bin/dataproc.sh \
parquet \
--output …
```
=> Bug 1594448 - Add avro support to parquet and mobile aggregates

mozaggregator/cli.py, mozaggregator/mobile.py, tests/test_mobile.py
I'd like to partition the datasets in a way that will be easy to validate and insert into BigQuery. This will otherwise create many small files.
=> Partition mobile aggregates to avoid excessive load during validation

mozaggregator/cli.py, mozaggregator/mobile.py, mozaggregator/trim_db.py, tests/test_db.py, tests/test_trim_db.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1596122)
Running on the dev database:
```
To retain 57382 tables...
----------------------------------------
submission_date_nightly_55_20171121
submission_date_beta_46_20171121
submission_date_beta_40_20171121
submission_date_release_41_20171121
submission_date_aurora_51_20171121
...
submission_date_nightly_61_20191120
submission_date_aurora_39_20191120
submission_date_beta_44_20191120
submission_date_nightly_42_20191120
submission_date_aurora_70_20191120
========================================
To trim 42641 tables...
----------------------------------------
submission_date_aurora_41_20150601
submission_date_nightly_41_20150601
submission_date_nightly_40_20150601
submission_date_aurora_40_20150601
submission_date_aurora_40_20150603 …
```
=>  Bug 1596122 - Add command to trim mozaggregator database

mozaggregator/cli.py
I think caching would help reduce the length of the current job in prerelease. `aggregates[1]` depends on `aggregates[0]`, both datasets are being counted, and both datasets are being mapped over for insertion into the database. It currently runs for 3.5 hours on 10x n1-standard-8. It would be useful to watch the server utilization to see where the job is being bottlenecked.
=> Cache aggregated datasets before insertion into database

Dockerfile, Dockerfile.dev, bin/README, bin/README.md, bin/export-avro.sh
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1606361)
This is tested using the following commands:
```bash
export GOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account.json
docker build -t mozagg:latest .
function run_export() {
local table=$1
local channels=$2
local date=$3
docker run \
--entrypoint bash \
-v $GOOGLE_APPLICATION_CREDENTIALS:/tmp/credentials \
-e GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials \
-it mozagg:latest \
gcloud auth activate-service-account --key-file /tmp/credentials && \
bin/export-avro.sh \
moz-fx-data-shar-nonprod-efed \
amiyaguchi-dev:avro_export \
gs://amiyaguchi-dev/avro-mozaggregator \
"$table" \
"$channels" \
"$date"
}
run_export saved_session_v4 "'nightly', 'beta'" 2019-12-29
run_export mobile_metrics_v1 "" 2019-12-29
NUM_WORKERS=3 …
```
=> Bug 1606361 - Update docker image for exporting avro data
